#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define question_length 1000
#define answer_length 50
#define explain_length 10000
#define no_players 10
#define no_questions 40

typedef struct {
    char question[question_length];
    char answer[answer_length];
    char explain[explain_length];
} Question;

typedef struct {
    int id;
    char name[50];
    int score;
} Player;

Question questions[no_questions] = {
    {"\nWhich among the following are Green House Gases (GHG)?\n1. Surface ozone (O_{3})\n2. Ammonia (N*H_{1})\n3. Methane (C*H_{4})\n4. Carbon monoxide (CO)\n5. Nitrous oxide (N_{2}*O)\n\nChoose the most appropriate answer from the options given below:\n\na) 1, 2 and 3 only\nb) 1, 3 and 5 only\nc) 2, 3 and 4 only\nd) 3, 4 and 5 only\n\n", "b", "-> Surface ozone (03) is a secondary GHG that is formed due to the interaction of sunlight with pollutants such as nitrogen oxides and volatile organic compounds.\n-> Methane (CH4) is a potent GHG that is emitted during various human activities such as agriculture, livestock farming, and fossil fuel production\n-> Nitrous oxide (N20) is another potent GHG that is emitted during agricultural practices, industrial processes, and fossil fuel combustion.\n-> Thus, Out of the options given, surface ozone (03), methane (CH4), and nitrous oxide (N20) are Green House Gases\nTherefore, the most appropriate answer is A, C, and E\n"},
    {"\nSelect the incorrect statement about ozone depletion over Antarctica\na. The polar stratospheric clouds provide a surface for ozone depletion\nb. Ozone depletion is maximum in summer season\nc. Unique weather conditions cause increased ozone depletion\nd. The chlorine radicals are the major cause of ozone breakdown\n\n", "b", "-> Ozone gas is continuously formed by the action of UV rays on molecular oxygen. It is also degraded into molecular oxygen in the stratosphere.\n-> There should be a balance between the production and degradation of ozone in the stratosphere.\n-> In 1980s atmospheric scientists working in Antarctica reported about the depletion of the ozone layer. It is commonly known as the ozone hole over the South Pole.\n-> It was found that a unique set of conditions was responsible for the ozone hole.\n"},
    {"\nWhat is the unit used to measure the quantity of ozone content in the atmosphere?\na. Einstein unit\t\tb. Poise\nc. Dobson unit\t\td. Becquerel\n\n", "c", "-> The average amount of ozone is around 300 Dobson units which means 3mm thick ozone.\n-> The ozone layer is a layer of the Earth's atmosphere in which the concentration of ozone gas is relatively high.\n-> This layer absorbs 93-99 percentage of the sun's high-frequency ultraviolet light, which is harmful to life on Earth.\n-> More than 91 percentage of the ozone of the Earth's atmosphere is present here.\n-> The ozone layer protects the health of humans and the ecosystem-py preventing harmful ultraviolet rays reaching from the sun to the earth.\n"},
    {"\nAt a typical urban site, the ground level ozone concentration would be maximum at what time of the day?\na. Morning\t\tb. Afternoon\nc. Evening\t\td. Night\n\n", "b", "-> It is created when two principal pollutants react in sunlight and still air. Volatile organic compounds (VOCs) and nitrogen oxides (NOx) are these two main pollutants.\n-> Its usual concentration is 20 to 30 parts per billion by volume.\n->  Summertime temperatures and increased sunlight cause more ozone to accumulate.\n-> In the summer, when direct sunlight is at its strongest, ozone levels are normally at their maximum in the afternoon.\n-> Thus, at a typical urban site, the ground level ozone concentration would be maximum in the Afternoon.\n"},
    {"\nOzone holes are more pronounced at the \na. Equator\t\tb. Tropic of Cancer\nc. Tropic of Capricorn\t\td. Poles\n\n", "d", "-> Ozone absorbs the harmful UltraViolet (UV) radiations from the sun eliminating a big threat to life forms on earth\n-> UV rays can cause skin cancer and other diseases and deformities in plants and animals.\n-> The ozone holes most commonly refer to the depletion over Antarctica, forming each year in September, October, and November, due to a set of special meteorological and chemical conditions that arise at the South Pole, and can reach sizes of around 20 to 25 million sq km.\n-> Hence, we can say that Ozone holes are more pronounced at the poles. Hence, Option 4 is correct\n-> Chlorofluorocarbons, Hydrochlorofluorocarbons, Carbon tetrachloride, Methyl chloroform, Methyl chloroform, Halons, Methyl bromide.\n-> Another pollutant we have added to the upper atmosphere that affects ozone is nitrogen oxides from airplane exhaust. So, above and beyond, the seasonal variations in ozone are more pronounced at the poles.\n"},
    {"\nGlass containers are generally not recommended for collecting rainwater samples. Why? \na. Glass containers are expensive\nb. Glass containers are not easy to maintain\nc. Glass containers affect the pH of the rain water\nd. All of the mentioned\n\n", "c", "-> Glass containers can change the pH of rainwater.\n-> They are not appropriate for sampling rainwater.\n"},
    {"\nWhich of the following gasses is the most responsible for acid rain? \na. Carbon dioxide and carbon monoxide are two types of gasses.\nb. Carbon dioxide and sulfur dioxide\nc. Nitrogen dioxide and sulfur dioxide\nd. Nitrous oxide and sulfur dioxide\n\n", "d", "Acid rain results when sulfur dioxide (SO2) and nitrogen oxides (NO2) are emitted into the atmosphere and transported by wind and air currents. The SO2 and NO2 react with water, oxygen and other chemicals to form sulfuric and nitric acids. These then mix with water and other materials before falling to the ground.\n\nFACT:\n\nAcid rain is the reason for the yellowness of the Taj Mahal"},
    {"\nWhere in India does it get the most rainfall each year? \na. Mawsynram\t\tb. Cherrapunji\nc. Siju\t\td. None of the above\n\n", "a", "Mawsynram is a place that receives the highest average rainfall in the world. It is located in Meghalaya. It receives the majority of its rainfall from the Bay of Bengal branch of the Indian monsoon. \nThe Bay of Bengal branch carries more moisture to the northeastern states causing heavy\n"},
    {"\nAcid Rain is created by emissions of \na. Sulfur dioxide\t\tb. Nitrogen oxide\nc. Both (A) and (B)\t\td. Carbon dioxide\n\n", "c", "Acid rain results when sulfur dioxide (SO2) and nitrogen oxides (NOX) are emitted into the atmosphere and transported by wind and air currents.\nThe SO2 and NOX react with water, oxygen and other chemicals to form sulfuric and nitric acids.\n"},
    {"\nAcid rain deplete \na. Calcium\t\tb. Magnesium\nc. Both (A) and (B)\t\td. None of the elements\n\n", "c", "Acid rain that seeps into the ground can dissolve nutrients, such as magnesium and calcium, that trees need to be healthy.\nAcid rain also causes aluminum to be released into the soil, which makes it difficult for trees to take up water.\n"},
    {"\nCutting of trees on large scale is called \na. Deforestation\t\tb. Reforestation\nc. Afforestation\t\td. None of these\n\n", "a", "Deforestation can be defined as the large-scale removal of trees from forests (or other lands) for the facilitation of human activities.\nIt is a serious environmental concern since it can result in the loss of biodiversity, damage to natural habitats, disturbances in the water cycle, and soil erosion.\n"},
    {"\nDeforestation generally decreases \na. Global Warming\t\tb. Drought\nc. Soil erosion\t\td. Rainfall\n\n", "d", "Deforestation generally decreases rainfall but increases global warming, drought, and soil erosion.\nDeforestation's impact on the earth's water cycle:- \nTrees play a key role in the water cycle by helping to keep a balance between the water on land and water in the atmosphere.\n"},
    {"\nDeforestation takes place by \na. Human activities\nb. Only by natural resources\nc. Both of these\nd. None of these\n\n", "a", "Deforestation is when humans remove or thin forests for lumber or to use the land where the trees stood for crops, grazing, extraction (mining, oil, or gas), or development as the population increases and people migrate.\n"},
    {"\nHow many trees does it take to provide a day supply of oxygen for 4 people? \na. 1\t\tb. 10\nc. 50\t\td. 100\n\n", "a", "It's proposed that ONE  LARGE TREE or two mature trees can provide oxygen for a family of 4"},
    {"\nIdentify the structure on the basis of the description given below.\nA pit is dug in the courtyard and it is made pucca. It is covered with a lid. Rainwater is collected in it through a pipe with a sieve attached to its mouth so that no dirt goes into it. This water is used for drinking after it is cleaned. \na. Baoli\t\tb. Johad\nc. Ghadsisar\t\td. Tanka\n\n", "d", "Rainwater harvest:\n\n-> Rainwater harvesting is a method to capture and store rainwater for various uses.\n-> It is also used to recharge groundwater aquifers.\n-> It is a low-cost and eco-friendly technique for preserving every drop of water by guiding the rainwater to borewells, pits and wells.\n\nTanka:\n\n-> Rainwater harvesting has been practised through various methods by different communities in the country for a long time.\n-> Traditional rainwater harvesting in rural areas is done by using surface storage bodies, like lakes, ponds, irrigation tanks, etc.\n-> In Rajasthan, rainwater harvesting structures locally known as Kund or Tanka (a covered underground tank) are constructed near or in the house or village to store harvested rainwater.\n-> In tanka a pucca is made then it is covered with a lid. • The pipe which fills the Tanka, its mouth is covered with a sieve, so that no dirt could enter the tanka.\n-> Thus, According to this given description, the structure is Tanka.\n"},
    {"\nThe structure used traditionally to harvest rain water in our country is \na. Tubewell\t\tb. Stepwell\nc. Borewell\t\td. Handpump\n\n", "b", "Irrigation:\n\n-> Irrigation is the controlled application of water through man-made systems to meet the water requirements of agriculture.\n-> It is an artificial application of water to crops or plants, especially when an agricultural field does not get enough water through rains.\n-> Traditional rainwater harvesting in rural areas is done by using surface storage bodies, like lakes, ponds, and irrigation tanks.\n\nStepwell:\n\n-> Stepwell or Baori are ponds with long steps that catch water and store them.\n-> It was an old Indian architecture from the 7th-19th century.\n-> These ponds are used as irrigation tanks for a long time, its mainly used during the seasonal fluctuation in water availability.\n->  Rainwater is stored in these wells during heavy rain.\n->  It is also used for drinking water and bathing, and sometimes acts as a sanctuary for travellers.\n-> Thus, the structure used traditionally to harvest rainwater in our country is a stepwell.\n"},
    {"\nThe collection of rainwater for future use is called \na. rainwater collection\nb. rainwater pumping\nc. Rain digging\nd. rainwater harvesting\n\n", "d", "-> Water scarcity will possibly pose the greatest challeng earth.\n-> It is because of increased demand coupled with shrinking supplies.\n-> There is over-utilisation of water due to the increasing population which is also one of the causes of increasing water pollution.\n->  Water pollution is the addition of unwanted material into water that makes it unfit for human consumption.\n-> With increasing reliance on water bodies for waste disposal etc, there has been ever-increasing water pollution.\n\nRainwater:\n\n-> Rainwater is known as the primary source or which gets collected at rivers and lakes and some of this water available as groundwater.\n-> Rainwater is considered the primary source of water because the just water from other sources like rivers or lakes can easily be replenished by rainwater.\n-> It is the only process by which new water is added to the ecosystem.\n-> Water harvesting is a practice to conserve water by collecting excess rainwater in an organized way.\n\nRain Water Harvesting:\n\n-> Water harvesting is a practice to conserve water by collecting rainwater in an organized way.\n-> The rainwater is not allowed to flow and get wasted but collected in tanks.\n-> The rainwater is not allowed to flow and get wasted but collected in tanks.\n-> The collected water through tubes is made to recharge gro\n->  Maintenance of groundwater is long term sustainable structure for water conservation.\n"},
    {"\nWhich of the following factors can contribute to sick building syndrome?\n1. Poor indoor air quality\n2. e-waste\n3.  Inadequate ventilation\n4. Poor water quality\n5.  Exposure to volatile organic compounds (VOCs)\n\nChoose the most appropriate answer from the options given below:\na. 1, 2 and 3\nb. 2, 3 and 4\nc. 1, 3 and 5\nd. 3, 4 and 5\n\n", "c", "-> Sick Building Syndrome (SBS) refers to a condition where occupants of a building experience health problems due to poor indoor air quality.\n-> This can be caused by inadequate ventilation, chemical pollutants, or biological contaminants.\n-> Sick building syndrome can be caused by a combination of factors, including poor indoor air quality, exposure to VOCs, and Inadequate ventilation.\n-> Other factors may include high humidity levels, mold and bacteria growth, and inadequate lighting.\n"},
    {"\nWhich one of the following air pollutants has a very strong affinity towards haemoglobin (Hb) of blood? \na.  Carbon dioxide (CO2)\t\tb. Carbon monoxide (CO)\nc.  Sulphur dioxide (SO2)\t\td. Nitrogen dioxide (NO2)\n\n", "b", "-> The air pollutant that has a very strong affinity towards haemoglobin (Hb) of blood is carbon monoxide (CO).\n-> CO is a toxic gas that is produced by Incomplete combustion of carbon-based fuels.\n-> It has a strong binding affinity to the haemoglobin in red blood cells, forming carboxyhemoglobin, which prevents oxygen from binding to haemoglobin and being transported to body tissues.\n-> This can lead to a condition called carbon monoxide poisoning, which can cause headaches, dizziness, nausea, and even death in high concentrations.\n"},
    {"\nFull form of PAN, a type of air pollutant, is- \na. Peroxyacetyl nitrates\nb. Peroxyacetyl nitrites\nc. Polycyclic acyl nitrates\td. Polycyclic acyl nitrites\n\n", "a", "->  PAN stands for Peroxyacyl nitrates, which is a type of air pollutant formed through a complex chain of reactions between volatile organic compounds (VOCs), nitrogen oxides (NOx), and sunlight.\n-> PAN is not directly emitted into the atmosphere but is formed through the photochemical reactions of VOCs and NOx in the presence of sunlight.\n-> PAN is a highly reactive compound that can cause serious health and environmental problems\n->  It is a major component of smog, which is a type of air pollution that can cause respiratory problems, eye irritation, and other health issues.\n-> PAN can also have harmful effects on vegetation and crops, leading to reduced yields and damage to the ecosystem.\n-> One of the significant sources of VOCs and NOx that contribute to the formation of PAN is automobile exhaust.\n->  Industrial processes, such as oil and gas production, chemicalmanufacturing, and printing, also emit large amounts of VOCs and NOX.\n-> Agricultural practices such as the use of fertilizers and pesticides, also contribute to the formation of PAN\n"},
    {"\nSmog is: \na. Ozone and smoke\t\tb. Vehicular pollutant\nc. Fog and smoke\t\td. Fog and ozone\n\n", "c", "-> Smog is Fog and smoke\n-> Smog is a type of intense air pollution that reduces visibility.\n->  The term 'Smog' was coined in the early 20th century and is derived from the words smoke and fog.\n-> Smog is a mixture of smoke (composed of minute particles of carbon, ash, and oil, etc. from coal combustion) and fog in suspended droplet form.\n-> It is the most common kind of air pollution that occurs in cities throughout the world.\n\nFACT:\n\nThere are 2 types of smog: Classical and Photochemical smog.\n-> Classical smog (London smog) occurs in a cool and humid climate. It is reducing in nature.\n-> Photochemical smog (Los Angeles smog) occurs in a sunny and dry climate. It is oxidising in nature.\n"},
    {"\nGlobal warming is caused by \na. methane\t\t\tb. nitrogen dioxide\nc. greenhouse gases\t\td. hydrogen\n\n", "c", "Greenhouse Effect: The solar energy trapped by the earth atmosphere and radiate it slowly so to cover our earth with a warm blanket. This is the natural process of the greenhouse effect on earth to maintain its temperature and makes the earth perfect for life.\n\nGlobal Warming:\n-> An increase in the average temperature of the earth surface due to the greenhouse effect is called global warming\n->  It also refers to the increase in the average temperature of the air and sea at the earth's surface.\n-> The greenhouse gases combined increased the temperature of planet earth so the correct option is greenhouse gases.\n"},
    {"\nThe Group of Eight (G-8 and formerly the G-6 or Group of Six and also the G - 7 group of Seven) is a forum, created by France in the year. \na. 1965\t\tb. 1970\nc. 1975\td. 1980\n", "c", "Group of eight(G8)\n-> This group came into existence in 1975, it was formerly the G-6 and G-7, created by France.\n-> These nations are France, Germany, Italy, the United Kingdom, Japan, the United states, Canada, and Russia.\n-> It refers to the group of eight highly industrialized nations.\n-> This group enables Presidents and Prime ministers, as well as their finance and foreign ministers, to discuss their international issues.\n-> These nations hold an annual meeting to foster consensus on global issues like economic growth and crisis management, global security, energy, and terrorism.\n-> Hence, it can be concluded that the Group of Eight (G-8) is a forum, created by France in 1975.\n"},
    {"\nWhich of the following gas emerges from the rice field? \na. Carbon di Oxide\t\tb. Methane\nc. Sulphur dioxide\t\td. Nitrogen\n\n", "b", "Methane emerges from the irrigated rice field. • Methane is considered one of the greenhouse gases.\nOther GHGs are carbon dioxide, methane, nitrous oxide, and fluorinated gases (which are synthetic).\n"},
    {"\nWhat is global warming? \na. increase in the average temperature of the Indian Ocean\nb. decrease in the average temperature of the Earth's atmosphere\nc. increase in the average temperature of the Earth's atmosphere and its oceans\nd. decrease of CO2 in environment\n\n", "c", "-> Global warming is the long-term warming of the planet's overall temperature.\n-> It is an increase in the average temperature of the Earth's atmosphere and its oceans.\n-> It occurs when carbon dioxide and other air pollutants collect in the atmosphere and absorb sunlight and solar radiation that have bounced off the earth's surface.\n-> Global warming causes climate change which poses a serious threat to life on earth in the forms of widespread flooding and extreme weather.\n-> It is a gradual increase in the earth's gradual temperature generally due to the greenhouse effect caused by increased levels of carbon dioxide, CFCs, and other pollutants.\n"},
    {"\nIdentify the correct sequence of continents in decreasing order of their yearly carbon dioxide emissions, at present \n1. Africa\t\t2. Asia\n3. Europe\t\t4. North America\n\nChoose the correct answer from the option given below\n\na. 2,4,1,3\t\tb. 2,4,3,1\nc. 4,2,3,1\t\td. 4,3,2,1\n\n", "b", "According to World Green House Gas Emission Data, the correct sequence of countries in decreasing order of their contribution to global carbon dioxide emissions is Asia, North America, Europe, and Africa.\n\nFACT:\n\nCarbon dioxide (C*O_{2}) makes up the vast majority of greenhouse gas emissions from the sector, but smaller amounts of methane (C*H_{4}) and nitrous oxide (N_{2}*O) are also emitted. These gases are released during the combustion of fossil fuels, such as coal, oil, and natural gas, to produce electricity.\n"},
    {"\nWhat does UNFCCC stand for? \na. United Nations Framework Control on Climate Change\nb. United Nations Framework Convention on Climate Change\nc. United Nations Framework Communications on Climate Change\nd. United Nations Framework Climate Communications Council\n\n", "b", "-> The UNFCCC entered into force on 21 March 1994.\n-> The 197 countries that have ratified the Convention are called Parties to the Convention.\n-> The objective of UNFCCC is to stabilize atmospheric concentrations of greenhouse gases at a level that will prevent dangerous interference with the climate system.\n-> The UNFCCC is a 'Rio Convention', one of two opened for signature at the 'Rio Earth Summit' in 1992 held in Rio de Janeiro, Brazil.\n"},
    {"\nWhich of the following ultraviolet rays is more dangerous? \na. UV-A\t\tb. UV-B\nc. UV-C\t\td. None of these\n\n", "b", "UV-C Rays are most dangerous because they penetrate the second layer of skin and causes skin cancer.\n\nFACT:\n\nUVC Rays:\n-> Shortest waves, usually do not penetrate the Earth's ozone layer\n-> 100 nm wavelength\n\nUVB Rays:\n-> Longer waves, that reach skin's surface. can cause surface tanning burning and signs of aging.\n-> 290nm wavelength\n\nUVA Rays:\n-> Even longer waves that can penetrate deep into the skin's surface , releasing free radicals and causing DNA changes that can result in skin cancers.\n-> 320nm wavelength\n"},
    {"\nThe abbreviation NMSHE, in the context of Climate Action Plan of Govt. of India, stands for \na. National Mission on Solar - Hydro Energy\nb. National Mission on Sustaining Himalayan Ecosystem\nc. National Mission on Sustainable Hydrogen Energy\nd. National Mission on Survey of Himalayan Ecosystem\n\n", "b", "-> The National Action Plan on Climate Change (NAPCC) has enunciated the launch of a National Mission for Sustaining the Himalayan Ecosystem (NMSHE).\n-> The Mission needs to deliver a better understanding of the coupling between the Himalayan ecosystem and the climate factors and provide inputs for Himalayan Sustainable development while addressing also the protection of a fragile ecosystem.\n-> This requires the joint effort of climatologists, glaciologists, and other experts.\n-> Exchange of information with the South Asian countries and countries sharing the Himalayan ecology will also be required.\n-> NMSHE aims to establish an observational and monitoring network for the Himalayan environment to assess freshwater resources and the health of the ecosystem.\n"},
    {"\nWhich of the following statements is/are true regarding Watershed Management' ?\n1. Conservation of groundwater and surface water\n2. Can be handled at an individual level\n3. Allocation of funds is needed to plan\n4. Framing of watershed policy for conserving water\n\na. 1 and 2\t\tb. 1, 3 and 4\nc. 1, 2 and 3\t\td. only 1\n\n", "b", "-> Watershed Management is a process that aims to protect and conserve water resources in a specific area.\n-> It involves taking care of both groundwater (water found underground) and surface water (water found in lakes, rivers, and other bodies of water).\n-> The main goal of watershed management is to ensure that there is enough clean water for various needs like drinking, farming, and supporting nature.\n-> It requires careful planning and implementation of strategies to prevent water pollution, manage water usage, and preserve the overall health of the watershed.\n-> Watershed management is not something that can be done by individuals alone; it requires the collective effort of communities, government organizations, and other stakeholders.\n"},
    {"\nBaoli refers to \na. Well\t\tb. Stepwell\nc. Pond\t\td. Stream\n\n", "b", "-> Baolis are stepwells, which are wells or ponds in which the people reach the water by going down a set of steps.\n-> Baolis were a traditional means of storing water in the drier parts of India.\n-> Separate baolis were constructed for drinking and bathing purposes.\n-> Most baolis were designed only for the purpose of water storage.\n"},
    {"\nWater is said to be scarce in an area if \na. every household gets water for daily use\nb. water comes to that area only via taps\nc. water received is unsafe for drinking and cooking\nd.  people can do washing and cleaning with the water received\n\n", "c", "-> The lack of sufficient water resources to meet regional water usage demands is known as water scarcity.\n-> Various factors, such as the expanding population, increased agricultural needs, industrial use, and the generation of electricity, all contribute to the rise in water demand.\n-> Water scarcity refers to a situation where the demand for water exceeds the available supply of water.\n-> This can lead to a lack of access to safe and clean drinking water, which can have serious consequences for human health and well- being.\n-> When there is water scarcity, people may be forced to drink water that is contaminated.\n-> Contamination with pollutants or pathogens, can cause diseases such as diarrhea, cholera, and typhoid fever.\n-> In some cases, people may have to travel long distances to collect water, which can be time-consuming and physically taxing, particularly for women and children.\n"},
    {"\nRadiocarbon dating is a technique used to estimate the age of \na. Rocks\t\tb. Soil\nc. Fossils\t\td. Buildings\n\n", "c", "-> When the body of a dead organism is buried in the soil, the soft parts of its body melt and the hard parts slowly turn into a stone known as fossils.\n-> Radiocarbon dating is the method of determining the age of living remains of animals and plants.\n-> The ratio between carbon-12 and carbon-14 is extracted.\n-> Carbon-14 is a radioactive isotope of carbon having a half-life of 5730 years.\n-> Carbon dating is used to determine the extent of radioactive substances.\n-> This technique was invented in 1949 by Williard Libby and his colleagues of the University of Chicago and was awarded the Nobel Prize in chemistry in 1960.\n"},
    {"\nWhich of the following birds is a critically endangered species? \na. Great Indian Bustard\nb. Cuckoo\nc. Peacock\nd. Crow\n\n", "a", "-> IUCN, International Union for Conservation of Nature, was established on 5 October 1948.\n-> The IUCN Red List of Threatened Species was founded in 1964.\n-> It is the world's most comprehensive inventory of the global conservation status of biological species.\n-> The Great Indian Bustard (GIB), the State bird of Rajasthan.\n-> It is considered India's most critically endangered bird.\n"},
    {"\nThe extinction of passenger pigeon was due to \na. Increased number of predatory birds\nb. Over exploitation by humans\nc. Non-availabiliy of the food\nd. Bird flu virus infection\n\n", "b", "-> A species is said to be extinct when it is not seen in the wild for 50 years at a stretch\n-> Extinction occurs when species are diminished because of environmental forces (habitat fragmentation, global change, natural disaster, overexploitation of species for human use) or because of evolutionary changes in their members Igenetic inbreeding, poor reproduction, decline in population numbers).\n-> The Passenger Pigeon, once one of the most abundant birds in the world, was pushed to extinction by overhunting and habitat destruction.\n"},
    {"\nThe term alpha diversity refers to \na. Genetic diversity\nb. Community and ecosystem diversity\nc. Species diversity\nd. Diversity among the plants\n\n", "c", "-> Alpha diversity (a-diversity) is defined as the mean diversity of species in different sites or habitats on a local scale.\n-> This term was coined by Robert Harding Whittaker along with other connected terminologies such as beta diversity (B-diversity) and gamma diversity (y-diversity).\n-> Species richness, which is the count of the number of species present in an area, is the simplest measure of alpha diversity.\n"},
    {"\nIn ecotone some species become abundant \na. Sibling species\nb. Endemic species\nc. Rare species\nd. Edge species\n\n", "d", "-> Ecotones are areas or zones of transition between two ecological communities, ecosystems, and or ecological regions.\n-> Sometimes the number of species and the population density of some of the species in the ecotone is much greater than in other communities. This is called the edge effect.\n-> The organisms which occur primarily or most abundantly in ecotone are known as edge species.\n"},
    {"\nWhich radiation may be one reason why the house sparrow is disappearing. \na. X-ray\t\tb. Cosmic rays\nc. Cell phone\t\td. Ultra violet rays\n\n", "c", "-> A few years back the population of sparrow birds started to decline and they were not seen that commonly.\n-> They are known to be sensitive to magnetic radiation.\n-> An increasing number of cell phone towers in cities apparently are bringing down their populations.\n-> The microwaves (300 MHz to 300 GHz) emitted by cell phone towers and handsets have been found to be responsible for damaging the eggs and embryos of sparrows.\n-> Several countries have observed a reduction in bird diversity coinciding with the increase in cellular mobile base stations.\n"},
    {"\nAnimal Disease Research Institute is situated in: \na. Ranpur (Nayagarh)\nb. Brahmagiri (Puri)\nc. Phulnakhara (Cuttack)\nd. Chandrapur (Rayagada)\n\n", "c", "The Animal Disease Research Institute, Phulnakhara, Cuttack was conceptualized by the Director of Animal Husbandry and Veterinary Services, Odisha and established by an order of the Government of Odisha.\n"},
    {"\nBreeding of fish in specially constructed tanks and ponds is known as \na. Pisciculture\t\tb. Horticulture\nc. Sericulture\t\td. Viticulture\n\n", "a", "-> Fishes are a valuable and easily accessible source of food, rich in protein, highly nutritious, and easily digestible.\n-> As aquatic animals, they are abundantly available from the sea, rivers, lakes, ponds, and marshes.\n-> Aquaculture is the production of useful aquatic plants and animals such as fishes, prawns, shrimps, lobsters, crabs, molluscs by the proper utilization of small and large bodies of water.\n-> Pisciculture is the production and breeding of fishes by men in ponds.\n"},
};

void display_question(Question *question) {
    printf("Question: %s\n", question->question);
}

void process_answer(Question *question, Player *player) {
    char entered_answer[answer_length];
    printf("%s, enter your answer: ", player->name);
    scanf("%s", entered_answer);

    if (strcmp(entered_answer, question->answer) == 0) {
        player->score += 1;
        printf("Correct answer!\n\n%s\n\n",question->explain);
    } else {
        printf("Wrong answer!\n\n%s\n\n",question->explain);
    }
}

void randomize_questions() {
    srand(time(NULL));

    for (int i = 0; i < no_questions; i++) {
        int j = rand() % no_questions;
        Question temp = questions[i];
        questions[i] = questions[j];
        questions[j] = temp;
    }
}

int main() {
    int num_players;
    Player players[no_players];
    int i, j, a;

    printf("Enter the no. of players: ");
    scanf("%d", &num_players);

    for (i = 0; i < num_players; i++) {
        printf("Enter the name of player %d: ", i + 1);
        scanf("%s", players[i].name);
        players[i].id = i + 1;
        players[i].score = 0;
    }

    //randomize_questions();

    for (j = 0; j < num_players; j++) {
            printf("\nPlayer %d: %s\n\n", players[j].id, players[j].name);
            
        randomize_questions();
        
        for (i = 0; i < 10; i++) {
            display_question(&questions[i]);
            process_answer(&questions[i], &players[j]);
            printf("Press '1' to continue\nPress '0' to end\n");
            scanf("%d",&a);
            if(a==1){
                continue;
            }
            else{
                break;
            }
            }

    }

    printf("\nQuiz Results\n\n");
    for (i = 0; i < num_players; i++) {
        printf("Player %d: %s, Score: %d\n", players[i].id, players[i].name, players[i].score);
    }

    return 0;
}
